server:
  port: 8089

spring:
  application:
    name: recommendation-service
  data:
    redis:
      host:
      port:

resilience4j:
  circuitbreaker:
    instances:
      naver-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: count-based
        sliding-window-size: 100
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 5
      vertex-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: count-based
        sliding-window-size: 100
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 5
  timelimiter:
    instances:
      naver-service:
        timeout-duration: 3s
        cancel-running-future: true
      vertex-service:
        timeout-duration: 5s
        cancel-running-future: true

gcp:
  project-id:
  location:
  vertex-ai:
    endpoint-id:

naver:
  api:
    client-id:
    client-secret: