server:
  port: 8089

spring:
  application:
    name: recommendation-service
  data:
    redis:
      host:
      port:

resilience4j:
  circuitbreaker:
    instances:
      naver-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: count-based
        sliding-window-size: 20
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5
      vertex-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: count-based
        sliding-window-size: 20
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5

gcp:
  project-id:
  location:
  vertex-ai:
    endpoint-id:

naver:
  api:
    client-id:
    client-secret: