server:
  port: 8089
  shutdown: graceful

spring:
  application:
    name: recommendation-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

resilience4j:
  circuitbreaker:
    instances:
      naver-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: count-based
        sliding-window-size: 100
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 5
      vertex-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: count-based
        sliding-window-size: 100
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 5
  timelimiter:
    instances:
      naver-service:
        timeout-duration: 3s
        cancel-running-future: true
      vertex-service:
        timeout-duration: 5s
        cancel-running-future: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}"

gcp:
  project-id: "${GCP_PROJECT_ID:}"
  location: "${GCP_LOCATION:us-central1}"
  vertex-ai:
    endpoint-id: "${GCP_VERTEX_AI_ENDPOINT_ID:}"

naver:
  api:
    client-id: "${NAVER_CLIENT_ID:}"
    client-secret: "${NAVER_CLIENT_SECRET:}"

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  endpoints:
    web:
      exposure:
        include: "health, prometheus"

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: "${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}"